# This is a basic workflow to help you get started with Actions

name: test_workflow_dispatch

# Controls when the workflow will run
on: [workflow_dispatch]
  # Triggers the workflow on push or pull request events but only for the main branch

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  job1:
    name: First Job
    runs-on: ubuntu-latest
    steps:
      - name: Step 1
        uses: actions/checkout@v2
      - name: Step 2
        run: echo "Hello Arijit"
