name: Daily-Cron-Integration-Test
on:
#  pull_request:
#    branches:
#      - master
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        description: Select a test environment
        options:
          - DEV
          - QA
          - STAGE
          - PROD
      test_type:
        type: choice
        description: Select a test type
        options:
          - PAYROLL
          - ADDRESSCLEANSE
          - BOTH

jobs:
  daily-cron-integration-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Print Selected environment
        run: echo "Environment::${{ github.event.inputs.environment }}"
      - name: Print Selected test type
        run: echo "Test type::${{ github.event.inputs.test_type }}"
      - if: github.event.inputs.environment == 'QA'
        name: Running QA environment
        run: echo "I am in QA"
      - name: Goodbye
        run: echo "Bye Arijit"
