name: Daily-Cron-Integration-Test
on:
#  pull_request:
#    branches:
#      - master
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        description: Select a test environment
        options:
          - DEV
          - QA
          - STAGE
          - PROD
      test_type:
        type: choice
        description: Select a test type
        options:
          - PAYROLL
          - ADDRESSCLEANSE
          - BOTH

jobs:
  daily-cron-integration-test:
    env:
      TEST_ENV_VARIABLE: ${{ github.event.inputs.environment }}
      TEST_TYPE_VARIABLE: ${{ github.event.inputs.test_type }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Print Selected environment
        run: echo "Environment::$TEST_ENV_VARIABLE"
      - name: Print Selected test type
        run: echo "Test type::$TEST_TYPE_VARIABLE"
      - if: ${{env.TEST_ENV_VARIABLE}} == 'QA'
        name: Running QA environment
        run: echo "I am in QA"
      - name: Goodbye
        run: echo "Bye Arijit"
