# This is a basic workflow to help you get started with Actions

name: first

# Controls when the workflow will run
on: [push]
  # Triggers the workflow on push or pull request events but only for the main branch

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  job1:
    name: First Job
    runs-on: ubuntu-latest
    steps:
      - name: Step 1
        uses: actions/checkout@v2
      - name: Step 2
        run: env | sort
  job2:
    name: Second job
    runs-on: windows-latest
    steps:
      - name: Step 1
        uses: actions/checkout@v2
      - name: Step 2
        run: "Get-ChildItem Env: | Sort-Object Name"
