name: Daily-Cron-Integration-Test
on:
#  pull_request:
#    branches:
#      - master
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        description: Select a test environment
        options:
          - DEV
          - QA
          - STAGE
          - PROD

jobs:
  daily-cron-integration-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Selected environment
        run: echo "Environment::${{ github.event.inputs.environment }}"
      - name: Goodbye
        run: echo "Bye Arijit"
